# Generated by Django 4.1.2 on 2022-12-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_satId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Satellite Location'),
        ),
    ]
